<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WsDeliveryOrderWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/WsDeliveryOrderWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/WsDeliveryOrderWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://wsdeliveryorder/">
    <import location="http://localhost:8080/TiendaElectronica/WsDeliveryOrder?WSDL" namespace="http://wsdeliveryorder/"/>
    <plnk:partnerLinkType name="WsDeliveryOrderLinkType">
        <plnk:role name="WsDeliveryOrderRole" portType="ns:WsDeliveryOrder"/>
    </plnk:partnerLinkType>
</definitions>
